title: "ForgetfulNUS"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-W16-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
